In [18]:
from tensorflow.keras.preprocessing.text import one_hot

In [19]:
## sentences
sent = [
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am a good boy',
    'I am a good developer',
    'understand the meaning of words',
    'your videos are good'
]

In [20]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [21]:
## Define the vocabulary size
voc_size = 10000

In [22]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [23]:
## One-hot encode the sentences
one_hot_sent = [one_hot(words, voc_size) for words in sent]

In [24]:
one_hot_sent

[[7991, 8853, 7440, 4565],
 [7991, 8853, 7440, 4051],
 [7991, 9744, 7440, 6491],
 [361, 6860, 6876, 2451, 9427],
 [361, 6860, 6876, 2451, 1389],
 [9983, 7991, 9475, 7440, 1980],
 [4919, 9222, 8285, 2451]]

In [25]:
## Word Embedding Representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.models import Sequential
from tensorflow.keras.utils import pad_sequences

In [26]:
import numpy as np

In [27]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_sent, padding='pre', maxlen=sent_length)
embedded_docs

array([[   0,    0,    0,    0, 7991, 8853, 7440, 4565],
       [   0,    0,    0,    0, 7991, 8853, 7440, 4051],
       [   0,    0,    0,    0, 7991, 9744, 7440, 6491],
       [   0,    0,    0,  361, 6860, 6876, 2451, 9427],
       [   0,    0,    0,  361, 6860, 6876, 2451, 1389],
       [   0,    0,    0, 9983, 7991, 9475, 7440, 1980],
       [   0,    0,    0,    0, 4919, 9222, 8285, 2451]], dtype=int32)

In [28]:
## Feature Representation
dim=10

In [31]:
model=Sequential()
model.add(Embedding(voc_size, dim, input_shape=(sent_length,)))
model.compile('adam', 'mse')

c:\Users\saksh\OneDrive\Desktop\DS ML NLP\venv\Lib\site-packages\keras\src\layers\core\embedding.py:100: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [32]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [34]:
embedded_docs

array([[   0,    0,    0,    0, 7991, 8853, 7440, 4565],
       [   0,    0,    0,    0, 7991, 8853, 7440, 4051],
       [   0,    0,    0,    0, 7991, 9744, 7440, 6491],
       [   0,    0,    0,  361, 6860, 6876, 2451, 9427],
       [   0,    0,    0,  361, 6860, 6876, 2451, 1389],
       [   0,    0,    0, 9983, 7991, 9475, 7440, 1980],
       [   0,    0,    0,    0, 4919, 9222, 8285, 2451]], dtype=int32)

In [33]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 318ms/step


array([[[ 0.03316006,  0.02891878, -0.04842825,  0.02187527,
         -0.04726676,  0.02704448, -0.01737285, -0.01545031,
          0.02179385,  0.02589351],
        [ 0.03316006,  0.02891878, -0.04842825,  0.02187527,
         -0.04726676,  0.02704448, -0.01737285, -0.01545031,
          0.02179385,  0.02589351],
        [ 0.03316006,  0.02891878, -0.04842825,  0.02187527,
         -0.04726676,  0.02704448, -0.01737285, -0.01545031,
          0.02179385,  0.02589351],
        [ 0.03316006,  0.02891878, -0.04842825,  0.02187527,
         -0.04726676,  0.02704448, -0.01737285, -0.01545031,
          0.02179385,  0.02589351],
        [-0.00788735,  0.01005298, -0.01254878, -0.01222618,
         -0.01373722,  0.03186209,  0.02614618, -0.00625416,
         -0.0450688 ,  0.00781089],
        [ 0.02092418, -0.00491712, -0.03559184,  0.0206197 ,
          0.03842664,  0.01267207,  0.03157924,  0.0378463 ,
         -0.00469287,  0.04998389],
        [ 0.04753574,  0.04766491,  0.04133705, -0.0

In [35]:
embedded_docs[0]

array([   0,    0,    0,    0, 7991, 8853, 7440, 4565], dtype=int32)

In [42]:
model.predict(np.array([embedded_docs[0]]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step


array([[[ 0.03316006,  0.02891878, -0.04842825,  0.02187527,
         -0.04726676,  0.02704448, -0.01737285, -0.01545031,
          0.02179385,  0.02589351],
        [ 0.03316006,  0.02891878, -0.04842825,  0.02187527,
         -0.04726676,  0.02704448, -0.01737285, -0.01545031,
          0.02179385,  0.02589351],
        [ 0.03316006,  0.02891878, -0.04842825,  0.02187527,
         -0.04726676,  0.02704448, -0.01737285, -0.01545031,
          0.02179385,  0.02589351],
        [ 0.03316006,  0.02891878, -0.04842825,  0.02187527,
         -0.04726676,  0.02704448, -0.01737285, -0.01545031,
          0.02179385,  0.02589351],
        [-0.00788735,  0.01005298, -0.01254878, -0.01222618,
         -0.01373722,  0.03186209,  0.02614618, -0.00625416,
         -0.0450688 ,  0.00781089],
        [ 0.02092418, -0.00491712, -0.03559184,  0.0206197 ,
          0.03842664,  0.01267207,  0.03157924,  0.0378463 ,
         -0.00469287,  0.04998389],
        [ 0.04753574,  0.04766491,  0.04133705, -0.0